import { type FormatDetector, getChunk } from '../types';
import { extractComfyUIParams } from '../comfyui/graph-trace';
import {
  extractWorkflowProvenance, classifyComfyUIWorkflow, TENSORART_NODE_TYPES,
} from '../comfyui/provenance';

export const comfyUiDetector: FormatDetector = {
  name: 'ComfyUI',
  detect(chunks) {
    const prompt = getChunk(chunks, 'prompt');
    if (!prompt) return false;
    try {
      const sanitized = prompt
        .replace(/:\s*NaN/g, ': null')
        .replace(/:\s*Infinity/g, ': null')
        .replace(/:\s*-Infinity/g, ': null');
      const parsed = JSON.parse(sanitized);
      return typeof parsed === 'object' && parsed !== null;
    } catch {
      return false;
    }
  },
  async parse(chunks) {
    const promptChunk = getChunk(chunks, 'prompt')!;
    const workflowChunk = getChunk(chunks, 'workflow');
    const aiData: Record<string, any> = {};

    // Sanitize NaN/Infinity values that break JSON.parse
    const sanitized = promptChunk
      .replace(/:\s*NaN/g, ': null')
      .replace(/:\s*Infinity/g, ': null')
      .replace(/:\s*-Infinity/g, ': null');

    const workflow = JSON.parse(sanitized);
    aiData.comfyui_workflow = workflowChunk ? JSON.parse(workflowChunk) : workflow;
    // Default to ComfyUI; override with service-specific signals below
    aiData.workflow_type = 'ComfyUI';

    // UUID pattern used by ArcEnCiel for lora names and SaveImage prefixes
    const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/i;

    for (const nodeData of Object.values(workflow)) {
      const node = nodeData as any;
      const inputs = node?.inputs ?? {};

      // TensorArt: proprietary node class_types or EMS-<id> model naming
      if (TENSORART_NODE_TYPES.has(node?.class_type)) { aiData.workflow_type = 'TensorArt'; break; }
      const ckpt = inputs.ckpt_name;
      if (typeof ckpt === 'string' && /EMS-\d+/i.test(ckpt)) { aiData.workflow_type = 'TensorArt'; break; }

      // ArcEnCiel: SaveImage prefix is "generator/{uuid}", and/or lora names
      // are UUID-prefixed (e.g. "ab234327-..._LoraName.safetensors").
      // ArcEnCiel runs standard ComfyUI nodes so there are no proprietary class_types.
      // NOTE: no API integration yet — pending contact with the ArcEnCiel team.
      if (node?.class_type === 'SaveImage') {
        const prefix = inputs.filename_prefix;
        if (typeof prefix === 'string' && /^generator\/[0-9a-f-]{36}$/i.test(prefix)) {
          aiData.workflow_type = 'ArcEnCiel';
        }
      }
      if (aiData.workflow_type !== 'ArcEnCiel' && typeof inputs.lora_name === 'string' && UUID_RE.test(inputs.lora_name)) {
        aiData.workflow_type = 'ArcEnCiel';
      }
    }

    // If a Workflow chunk exists alongside the Prompt chunk, extract per-node
    // provenance (cnr_id / aux_id). ComfyUI ≥1.26 embeds this automatically;
    // it lets us resolve node origins without GitHub code search.
    const provenance = workflowChunk ? extractWorkflowProvenance(workflowChunk) : undefined;

    // Scan entire workflow JSON for Civitai URN:AIR resource identifiers.
    // Format: urn:air:{baseModel}:{type}:civitai:{modelId}@{versionId}
    // These appear in lora_name, model_name, and other input fields.
    const URN_AIR_RE = /urn:air:([^:]+):([^:]+):civitai:(\d+)@(\d+)/g;
    const workflowStr = JSON.stringify(workflow);
    const seenUrns = new Set<string>();
    const civitaiUrnResources: Array<{ urn: string; baseModel: string; type: string; modelId: string; versionId: string }> = [];
    for (const m of workflowStr.matchAll(URN_AIR_RE)) {
      if (!seenUrns.has(m[0])) {
        seenUrns.add(m[0]);
        civitaiUrnResources.push({ urn: m[0], baseModel: m[1], type: m[2], modelId: m[3], versionId: m[4] });
      }
    }
    if (civitaiUrnResources.length > 0) {
      aiData.civitai_urn_resources = civitaiUrnResources;
      // URN:AIR presence is authoritative: this workflow was generated by Civitai
      if (aiData.workflow_type === 'ComfyUI') aiData.workflow_type = 'Civitai';
    }

    // Classify all class_types FIRST (extension-map + Workflow provenance),
    // so the traversal in extractComfyUIParams can recognise custom nodes.
    const nodeInfo = await classifyComfyUIWorkflow(workflow, provenance);
    if (nodeInfo) {
      aiData.comfyui_nodes = nodeInfo;
    }

    // Extract useful parameters from workflow, feeding the classifications
    // in so Phase 3 can treat known custom nodes with text-shaped inputs as
    // candidate text encoders.
    const extracted = extractComfyUIParams(workflow, nodeInfo?.classifications ?? {});
    Object.assign(aiData, extracted);
    // Restore workflow_type — extractComfyUIParams doesn't set it but Object.assign
    // could theoretically clobber it if the extracted object ever grows that key.
    if (!aiData.workflow_type) aiData.workflow_type = 'ComfyUI';

    return aiData;
  },
};
